#!/bin/sh
set -efu

text_en="Once upon a time, in a quiet village nestled between rolling hills and sparkling rivers, there lived a clever fox named Felix. Felix was known throughout the village for his cunning tricks and playful antics. Every morning, he would sneak through the meadows, darting past rabbits and chickens, always careful to avoid the farmer's watchful eyes. Despite his mischievous ways, Felix had a kind heart and often shared his clever solutions with friends in need. One day, a heavy storm swept through the valley, leaving many paths muddy and rivers swollen. Felix saw his chance to help: he guided lost ducklings back to their pond, and showed the frightened kittens how to find shelter under the sturdy oak trees. The villagers watched in amazement as the fox moved gracefully through the rain-soaked fields, his orange fur glistening and his sharp eyes alert. By the time the storm passed, the village had gained a newfound respect for Felix. Tales of his bravery spread far and wide, carried by wandering merchants and whispered by children as they played near the cobblestone streets. Nights in the village were quiet once more, but the story of Felix, the fox who danced through storm and shadow, continued to inspire laughter, cleverness, and courage in the hearts of all who heard it."

echo "$text_en" | python3 sort.py

text_de="In einem kleinen Dorf, versteckt zwischen sanften Hügeln und klaren Bächen, lebte ein listiger Fuchs namens Fritz. Fritz war bekannt für seine cleveren Streiche und seine verspielte Natur. Jeden Morgen schlich er durch die Wiesen, huschte an Hasen und Hühnern vorbei und achtete dabei genau auf die wachsamen Augen des Bauern. Trotz seiner schelmischen Art hatte Fritz ein gutes Herz und half oft Freunden in Not. Eines Tages fegte ein heftiger Sturm durch das Tal, die Wege wurden schlammig und die Flüsse traten über die Ufer. Fritz sah seine Chance, zu helfen: Er führte verlorene Entenküken zurück zu ihrem Teich und zeigte den ängstlichen Kätzchen, wie sie Schutz unter den starken Eichen finden konnten. Die Dorfbewohner beobachteten erstaunt, wie der Fuchs anmutig durch die regengetränkten Felder sprang, sein orangefarbenes Fell glänzte und seine scharfen Augen waren stets wachsam. Nachdem der Sturm vorübergezogen war, gewann das Dorf großen Respekt für Fritz. Geschichten über seine Tapferkeit verbreiteten sich weit und breit, getragen von reisenden Händlern und von Kindern, die beim Spielen auf den Kopfsteinpflasterstraßen flüsterten. Die Nächte im Dorf waren wieder ruhig, aber die Erzählung von Fritz, dem Fuchs, der durch Sturm und Schatten tanzte, inspirierte weiterhin Lachen, Cleverness und Mut in den Herzen aller, die davon hörten."

echo "$text_de" | python3 sort.py -l de

text_hi="एक समय की बात है, एक शांत गाँव में, जो हरे-भरे पहाड़ों और बहती नदियों के बीच बसा था, एक चालाक लोमड़ी रहती थी जिसका नाम फेलेक्स था। फेलेक्स अपनी चतुराई और खेल-कूद के लिए पूरे गाँव में प्रसिद्ध थी। हर सुबह वह घास के मैदानों में दौड़ती, खरगोशों और मुर्गियों के पास से निकलती और हमेशा किसान की सतर्क निगाहों से बचती। अपनी शरारतों के बावजूद, फेलेक्स का दिल बहुत अच्छा था और वह अक्सर अपने दोस्तों की मदद करती थी। एक दिन, एक तेज तूफ़ान ने घाटी में कहर ढाया, रास्ते कीचड़ से भर गए और नदियाँ उफन गईं। फेलेक्स ने मदद करने का अवसर देखा: उसने खोए हुए बतख के बच्चों को उनके तालाब तक पहुँचाया और डरी हुई बिल्लियों को मजबूत ओक के पेड़ों के नीचे आश्रय दिखाया। गाँव वाले आश्चर्यचकित होकर देखते रहे कि कैसे लोमड़ी बारिश भरे खेतों में चपलता से घूम रही थी, उसकी नारंगी फर चमक रही थी और उसकी तेज आँखें सतर्क थीं। जब तूफ़ान खत्म हुआ, गाँव वालों ने फेलेक्स के लिए सम्मान बढ़ाया। उसकी बहादुरी की कहानियाँ दूर-दूर तक फैल गईं, घूमते व्यापारियों द्वारा सुनाई गई और बच्चों द्वारा जो पत्थर की सड़कों पर खेलते समय फुसफुसाते। गाँव में रातें फिर से शांत हो गईं, लेकिन फेलेक्स की कहानी, वह लोमड़ी जो तूफ़ान और छाया में नाचे, सभी के दिलों में हँसी, बुद्धिमानी और साहस भरती रही।
"

echo "$text_hi" | python3 sort.py -l hi

text_dk="Engang for længe siden, i en lille landsby mellem bløde bakker og glitrende floder, boede en klog ræv ved navn Felix. Felix var kendt i hele landsbyen for sine snedige påfund og legende natur. Hver morgen sneg han sig gennem markerne, løb forbi kaniner og høns, altid opmærksom på bondens vågne øjne. På trods af sine drilske vaner havde Felix et godt hjerte og hjalp ofte venner i nød. En dag fejede en kraftig storm gennem dalen, og stierne blev mudrede, mens floderne steg over bredden. Felix så sin chance for at hjælpe: han guidede fortabte ællinger tilbage til deres dam og viste de skræmte kattekillinger, hvordan de kunne finde ly under de stærke egetræer. Landsbyboerne så forbløffet på, mens ræven bevægede sig yndefuldt gennem de regnvåde marker, dens orange pels glimtede, og dens skarpe øjne var altid årvågne. Da stormen havde lagt sig, havde landsbyen fået en ny respekt for Felix. Historier om hans mod spredte sig vidt og bredt, fortalt af rejsende handlende og hvisket af børn, der legede på de brostensbelagte gader. Nætterne i landsbyen blev stille igen, men fortællingen om Felix, ræven der dansede gennem storm og skygge, fortsatte med at inspirere latter, snilde og mod i hjertet af alle, der hørte den."
echo "$text_dk" | python3 sort.py -l da

text_nl="Er was eens, in een klein dorpje tussen glooiende heuvels en kabbelende rivieren, een slimme vos genaamd Felix. Felix stond bekend in het hele dorp om zijn sluwe streken en speelse karakter. Elke ochtend sloop hij door de velden, snelde langs konijnen en kippen, altijd oplettend voor de waakzame ogen van de boer. Ondanks zijn ondeugende aard had Felix een goed hart en hielp vaak vrienden in nood. Op een dag raasde een hevige storm door de vallei, de paden werden modderig en de rivieren traden buiten hun oevers. Felix zag zijn kans om te helpen: hij leidde verdwaalde eendjes terug naar hun vijver en liet de angstige kittens zien waar ze beschutting konden vinden onder de stevige eikenbomen. De dorpelingen keken vol verbazing toe terwijl de vos sierlijk door de regenachtige velden bewoog, zijn oranje vacht glanzend en zijn scherpe ogen altijd alert. Toen de storm voorbij was, had het dorp nieuw respect voor Felix gekregen. Verhalen over zijn moed verspreidden zich wijd en zijd, verteld door rondtrekkende handelaren en gefluisterd door kinderen die speelden op de kinderkopjesstraatjes. De nachten in het dorp werden weer rustig, maar het verhaal van Felix, de vos die danste door storm en schaduw, bleef lachen, slimheid en moed inspireren in de harten van iedereen die het hoorde."

echo "$text_nl" | python3 sort.py -l nl

text_fr="Il était une fois, dans un village paisible niché entre des collines ondulantes et des rivières scintillantes, un renard rusé nommé Félix. Félix était connu dans tout le village pour ses astuces ingénieuses et son esprit joueur. Chaque matin, il se faufilait à travers les prairies, filant devant les lapins et les poules, toujours vigilant aux yeux attentifs du fermier. Malgré ses manières espiègles, Félix avait un bon cœur et aidait souvent ses amis dans le besoin. Un jour, une violente tempête balaya la vallée, rendant les chemins boueux et les rivières gonflées. Félix vit là une occasion d'aider : il guida des canetons perdus jusqu'à leur étang et montra aux chatons effrayés comment trouver refuge sous les robustes chênes. Les villageois regardaient avec étonnement le renard se déplacer gracieusement à travers les champs trempés de pluie, son pelage orange brillant et ses yeux perçants toujours alertes. Une fois la tempête passée, le village avait acquis un nouveau respect pour Félix. Des récits de son courage se répandirent loin et large, portés par des marchands itinérants et chuchotés par les enfants jouant près des rues pavées. Les nuits dans le village redevinrent calmes, mais l'histoire de Félix, le renard qui dansait à travers la tempête et l'ombre, continua d'inspirer rire, ingéniosité et courage dans le cœur de tous ceux qui l'entendaient."
echo "$text_fr" | python3 sort.py -l fr
